runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
- url: /semantic
  static_dir: semantic
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /.*
  script: auto

